package org.domain.sdm.entity;

// Generated Jul 16, 2014 12:05:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SdmEmpresa generated by hbm2java
 */
@Entity
@Table(name = "SDM_empresa")
public class SdmEmpresa implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private Set<SdmInformeViaticos> sdmInformeViaticoses = new HashSet<SdmInformeViaticos>(
			0);
	private Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles = new HashSet<SdmInformeViaticoDetalle>(
			0);
	private Set<SdmEmpleado> sdmEmpleados = new HashSet<SdmEmpleado>(0);

	public SdmEmpresa() {
	}

	public SdmEmpresa(String codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public SdmEmpresa(String codigo, String nombre,
			Set<SdmInformeViaticos> sdmInformeViaticoses,
			Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles,
			Set<SdmEmpleado> sdmEmpleados) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.sdmInformeViaticoses = sdmInformeViaticoses;
		this.sdmInformeViaticoDetalles = sdmInformeViaticoDetalles;
		this.sdmEmpleados = sdmEmpleados;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdmEmpresa")
	public Set<SdmInformeViaticos> getSdmInformeViaticoses() {
		return this.sdmInformeViaticoses;
	}

	public void setSdmInformeViaticoses(
			Set<SdmInformeViaticos> sdmInformeViaticoses) {
		this.sdmInformeViaticoses = sdmInformeViaticoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdmEmpresa")
	public Set<SdmInformeViaticoDetalle> getSdmInformeViaticoDetalles() {
		return this.sdmInformeViaticoDetalles;
	}

	public void setSdmInformeViaticoDetalles(
			Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles) {
		this.sdmInformeViaticoDetalles = sdmInformeViaticoDetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdmEmpresa")
	public Set<SdmEmpleado> getSdmEmpleados() {
		return this.sdmEmpleados;
	}

	public void setSdmEmpleados(Set<SdmEmpleado> sdmEmpleados) {
		this.sdmEmpleados = sdmEmpleados;
	}

}
