package org.domain.sdm.entity;

// Generated Jul 16, 2014 12:05:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SdmInformeViaticoDetalle generated by hbm2java
 */
@Entity
@Table(name = "SDM_informe_viatico_detalle")
public class SdmInformeViaticoDetalle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1812837080046329605L;
	private long id;
	private SdmEmpresa sdmEmpresa;
	private SdmInformeViaticos sdmInformeViaticos;
	private SdmTipoServicio sdmTipoServicio;
	private SdmEmpleado sdmEmpleado;
	private SdmDivicion sdmDivicion;
	private SdmCentroCosto sdmCentroCosto;
	private SdmDelegacion sdmDelegacion;
	private Date fecha;
	private BigDecimal monto;
	private String descripcion;
	private String destino;
	private int correlativoInforme;

	public SdmInformeViaticoDetalle() {
	}

	public SdmInformeViaticoDetalle(long id, SdmEmpresa sdmEmpresa,
			SdmInformeViaticos sdmInformeViaticos,
			SdmTipoServicio sdmTipoServicio, SdmEmpleado sdmEmpleado,
			SdmDivicion sdmDivicion, SdmCentroCosto sdmCentroCosto,
			SdmDelegacion sdmDelegacion, Date fecha, BigDecimal monto,
			int correlativoInforme) {
		this.id = id;
		this.sdmEmpresa = sdmEmpresa;
		this.sdmInformeViaticos = sdmInformeViaticos;
		this.sdmTipoServicio = sdmTipoServicio;
		this.sdmEmpleado = sdmEmpleado;
		this.sdmDivicion = sdmDivicion;
		this.sdmCentroCosto = sdmCentroCosto;
		this.sdmDelegacion = sdmDelegacion;
		this.fecha = fecha;
		this.monto = monto;
		this.correlativoInforme = correlativoInforme;
	}

	public SdmInformeViaticoDetalle(long id, SdmEmpresa sdmEmpresa,
			SdmInformeViaticos sdmInformeViaticos,
			SdmTipoServicio sdmTipoServicio, SdmEmpleado sdmEmpleado,
			SdmDivicion sdmDivicion, SdmCentroCosto sdmCentroCosto,
			SdmDelegacion sdmDelegacion, Date fecha, BigDecimal monto,
			String descripcion, String destino, int correlativoInforme) {
		this.id = id;
		this.sdmEmpresa = sdmEmpresa;
		this.sdmInformeViaticos = sdmInformeViaticos;
		this.sdmTipoServicio = sdmTipoServicio;
		this.sdmEmpleado = sdmEmpleado;
		this.sdmDivicion = sdmDivicion;
		this.sdmCentroCosto = sdmCentroCosto;
		this.sdmDelegacion = sdmDelegacion;
		this.fecha = fecha;
		this.monto = monto;
		this.descripcion = descripcion;
		this.destino = destino;
		this.correlativoInforme = correlativoInforme;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_empresa", nullable = false)
	@NotNull
	public SdmEmpresa getSdmEmpresa() {
		return this.sdmEmpresa;
	}

	public void setSdmEmpresa(SdmEmpresa sdmEmpresa) {
		this.sdmEmpresa = sdmEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_inforne_viatico", nullable = false)
	@NotNull
	public SdmInformeViaticos getSdmInformeViaticos() {
		return this.sdmInformeViaticos;
	}

	public void setSdmInformeViaticos(SdmInformeViaticos sdmInformeViaticos) {
		this.sdmInformeViaticos = sdmInformeViaticos;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tipo_servicio", nullable = false)
	@NotNull
	public SdmTipoServicio getSdmTipoServicio() {
		return this.sdmTipoServicio;
	}

	public void setSdmTipoServicio(SdmTipoServicio sdmTipoServicio) {
		this.sdmTipoServicio = sdmTipoServicio;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_empleado", nullable = false)
	@NotNull
	public SdmEmpleado getSdmEmpleado() {
		return this.sdmEmpleado;
	}

	public void setSdmEmpleado(SdmEmpleado sdmEmpleado) {
		this.sdmEmpleado = sdmEmpleado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_divicion", nullable = false)
	@NotNull
	public SdmDivicion getSdmDivicion() {
		return this.sdmDivicion;
	}

	public void setSdmDivicion(SdmDivicion sdmDivicion) {
		this.sdmDivicion = sdmDivicion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_centro_costo", nullable = false)
	@NotNull
	public SdmCentroCosto getSdmCentroCosto() {
		return this.sdmCentroCosto;
	}

	public void setSdmCentroCosto(SdmCentroCosto sdmCentroCosto) {
		this.sdmCentroCosto = sdmCentroCosto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_delegacion", nullable = false)
	@NotNull
	public SdmDelegacion getSdmDelegacion() {
		return this.sdmDelegacion;
	}

	public void setSdmDelegacion(SdmDelegacion sdmDelegacion) {
		this.sdmDelegacion = sdmDelegacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "monto", nullable = false, precision = 8)
	@NotNull
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "descripcion", length = 200)
	@Length(max = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "destino", length = 50)
	@Length(max = 50)
	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	@Column(name = "correlativo_informe", nullable = false)
	public int getCorrelativoInforme() {
		return this.correlativoInforme;
	}

	public void setCorrelativoInforme(int correlativoInforme) {
		this.correlativoInforme = correlativoInforme;
	}

}
