package org.domain.sdm.entity;

// Generated Jul 16, 2014 12:05:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.OrderBy;
import org.hibernate.validator.NotNull;

/**
 * SdmInformeViaticos generated by hbm2java
 */
@Entity
@Table(name = "SDM_informe_viaticos")
public class SdmInformeViaticos implements java.io.Serializable {

	private long id;
	private SdmEmpresa sdmEmpresa;
	private SdmEmpleado sdmEmpleado;
	private SdmDivicion sdmDivicion;
	private SdmCentroCosto sdmCentroCosto;
	private SdmDelegacion sdmDelegacion;
	private Date fecha;
	private BigDecimal montoTotal;
	private boolean anulado;
	
	@Transient
	private SdmLiquidacionInformeViaticos sdmLiquidacionInformeViaticos ;
	
	private Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles = new HashSet<SdmInformeViaticoDetalle>(
			0);
	private Set<SdmLiquidacionInformeViaticos> sdmLiquidacionInformeViaticoses = new HashSet<SdmLiquidacionInformeViaticos>(
			0);

	public SdmInformeViaticos() {
	}

	public SdmInformeViaticos(long id, SdmEmpresa sdmEmpresa,
			SdmEmpleado sdmEmpleado, SdmDivicion sdmDivicion,
			SdmCentroCosto sdmCentroCosto, SdmDelegacion sdmDelegacion,
			Date fecha, BigDecimal montoTotal, boolean anulado) {
		this.id = id;
		this.sdmEmpresa = sdmEmpresa;
		this.sdmEmpleado = sdmEmpleado;
		this.sdmDivicion = sdmDivicion;
		this.sdmCentroCosto = sdmCentroCosto;
		this.sdmDelegacion = sdmDelegacion;
		this.fecha = fecha;
		this.montoTotal = montoTotal;
		this.anulado = anulado;
	}

	public SdmInformeViaticos(long id, SdmEmpresa sdmEmpresa,
			SdmEmpleado sdmEmpleado, SdmDivicion sdmDivicion,
			SdmCentroCosto sdmCentroCosto, SdmDelegacion sdmDelegacion,
			Date fecha, BigDecimal montoTotal, boolean anulado,
			Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles,
			Set<SdmLiquidacionInformeViaticos> sdmLiquidacionInformeViaticoses) {
		this.id = id;
		this.sdmEmpresa = sdmEmpresa;
		this.sdmEmpleado = sdmEmpleado;
		this.sdmDivicion = sdmDivicion;
		this.sdmCentroCosto = sdmCentroCosto;
		this.sdmDelegacion = sdmDelegacion;
		this.fecha = fecha;
		this.montoTotal = montoTotal;
		this.anulado = anulado;
		this.sdmInformeViaticoDetalles = sdmInformeViaticoDetalles;
		this.sdmLiquidacionInformeViaticoses = sdmLiquidacionInformeViaticoses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_empresa", nullable = false)
	@NotNull
	public SdmEmpresa getSdmEmpresa() {
		return this.sdmEmpresa;
	}

	public void setSdmEmpresa(SdmEmpresa sdmEmpresa) {
		this.sdmEmpresa = sdmEmpresa;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_empleado_emisor", nullable = false)
	@NotNull
	public SdmEmpleado getSdmEmpleado() {
		return this.sdmEmpleado;
	}

	public void setSdmEmpleado(SdmEmpleado sdmEmpleado) {
		this.sdmEmpleado = sdmEmpleado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_divicion", nullable = false)
	@NotNull
	public SdmDivicion getSdmDivicion() {
		return this.sdmDivicion;
	}

	public void setSdmDivicion(SdmDivicion sdmDivicion) {
		this.sdmDivicion = sdmDivicion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_centro_costo", nullable = false)
	@NotNull
	public SdmCentroCosto getSdmCentroCosto() {
		return this.sdmCentroCosto;
	}

	public void setSdmCentroCosto(SdmCentroCosto sdmCentroCosto) {
		this.sdmCentroCosto = sdmCentroCosto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_delegacion", nullable = false)
	@NotNull
	public SdmDelegacion getSdmDelegacion() {
		return this.sdmDelegacion;
	}

	public void setSdmDelegacion(SdmDelegacion sdmDelegacion) {
		this.sdmDelegacion = sdmDelegacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "monto_total", nullable = false, precision = 8)
	@NotNull
	public BigDecimal getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(BigDecimal montoTotal) {
		this.montoTotal = montoTotal;
	}

	@Column(name = "anulado", nullable = false)
	public boolean isAnulado() {
		return this.anulado;
	}

	public void setAnulado(boolean anulado) {
		this.anulado = anulado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdmInformeViaticos")
	@OrderBy(clause = "correlativo_informe ASC")
	public Set<SdmInformeViaticoDetalle> getSdmInformeViaticoDetalles() {
		return this.sdmInformeViaticoDetalles;
	}

	public void setSdmInformeViaticoDetalles(
			Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles) {
		this.sdmInformeViaticoDetalles = sdmInformeViaticoDetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdmInformeViaticos")
	public Set<SdmLiquidacionInformeViaticos> getSdmLiquidacionInformeViaticoses() {
		return this.sdmLiquidacionInformeViaticoses;
	}

	public void setSdmLiquidacionInformeViaticoses(
			Set<SdmLiquidacionInformeViaticos> sdmLiquidacionInformeViaticoses) {
		this.sdmLiquidacionInformeViaticoses = sdmLiquidacionInformeViaticoses;
	}
	
	@Transient
	public SdmLiquidacionInformeViaticos getSdmLiquidacionInformeViaticos() {
		return sdmLiquidacionInformeViaticos;
	}

	public void setSdmLiquidacionInformeViaticos(
			SdmLiquidacionInformeViaticos sdmLiquidacionInformeViaticos) {
		this.sdmLiquidacionInformeViaticos = sdmLiquidacionInformeViaticos;
	}

	
}
