package org.domain.sdm.entity;

// Generated Sep 21, 2014 5:40:54 PM by Hibernate Tools 3.4.0.CR1



import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;

/**
 * SdmLog generated by hbm2java
 */


@Entity
@Table(name = "SDM_log")
public class SdmLog implements java.io.Serializable {

	private long id;
	private Date fecha;
	private String ip;
	private String usuario;
	private String operacion;
	private String mensaje;
	private String tipo;
	private String nombreClase;
	private String referencia;

	public SdmLog() {
	}

	public SdmLog(long id, Date fecha, String ip, String usuario,
			String operacion, String mensaje, String tipo, String nombreClase,
			String referencia) {
		this.id = id;
		this.fecha = fecha;
		this.ip = ip;
		this.usuario = usuario;
		this.operacion = operacion;
		this.mensaje = mensaje;
		this.tipo = tipo;
		this.nombreClase = nombreClase;
		this.referencia = referencia;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "fecha", nullable = true )
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "ip", nullable = true, length = 50)
	@Length(max = 50)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "usuario", nullable = true, length = 50)
	@Length(max = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "operacion", nullable = true, length = 100)
	@Length(max = 100)
	public String getOperacion() {
		return this.operacion;
	}

	public void setOperacion(String operacion) {
		this.operacion = operacion;
	}

	@Column(name = "mensaje", nullable = true, length = 500)
	@Length(max = 200)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@Column(name = "tipo", nullable = true, length = 20)
	@Length(max = 20)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "nombre_clase", nullable = true, length = 50)
	@Length(max = 50)
	public String getNombreClase() {
		return this.nombreClase;
	}

	public void setNombreClase(String nombreClase) {
		this.nombreClase = nombreClase;
	}

	@Column(name = "referencia", nullable = true, length = 50)
	@Length(max = 50)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Override
	public String toString() {
		return "SdmLog [id=" + id + ", fecha=" + fecha + ", ip=" + ip
				+ ", usuario=" + usuario + ", operacion=" + operacion
				+ ", mensaje=" + mensaje + ", tipo=" + tipo + ", nombreClase="
				+ nombreClase + ", referencia=" + referencia + "]";
	}
	
	

}