package org.domain.sdm.entity;

// Generated 20/10/2014 08:48:14 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SdmParametro generated by hbm2java
 */
@Entity
@Table(name = "SDM_parametro")
public class SdmParametro implements java.io.Serializable {

	private String nombre;
	private String valor;

	public SdmParametro() {
	}

	public SdmParametro(String nombre, String valor) {
		this.nombre = nombre;
		this.valor = valor;
	}

	@Id
	@Column(name = "NOMBRE", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "VALOR", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
