package org.domain.sdm.entity;

// Generated Jul 16, 2014 12:05:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SdmRol generated by hbm2java
 */
@Entity
@Table(name = "SDM_rol")
public class SdmRol implements java.io.Serializable {

	private long id;
	private String etiqueta;
	private Set<SdmRolXUsuario> sdmRolXUsuarios = new HashSet<SdmRolXUsuario>(0);

	public SdmRol() {
	}

	public SdmRol(long id, String etiqueta) {
		this.id = id;
		this.etiqueta = etiqueta;
	}

	public SdmRol(long id, String etiqueta, Set<SdmRolXUsuario> sdmRolXUsuarios) {
		this.id = id;
		this.etiqueta = etiqueta;
		this.sdmRolXUsuarios = sdmRolXUsuarios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "etiqueta", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdmRol")
	public Set<SdmRolXUsuario> getSdmRolXUsuarios() {
		return this.sdmRolXUsuarios;
	}

	public void setSdmRolXUsuarios(Set<SdmRolXUsuario> sdmRolXUsuarios) {
		this.sdmRolXUsuarios = sdmRolXUsuarios;
	}

}
