package org.domain.sdm.entity;

// Generated Jul 16, 2014 12:05:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SdmRolXUsuarioId generated by hbm2java
 */
@Embeddable
public class SdmRolXUsuarioId implements java.io.Serializable {

	private long idRol;
	private long idUsuario;

	public SdmRolXUsuarioId() {
	}

	public SdmRolXUsuarioId(long idRol, long idUsuario) {
		this.idRol = idRol;
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_rol", nullable = false)
	public long getIdRol() {
		return this.idRol;
	}

	public void setIdRol(long idRol) {
		this.idRol = idRol;
	}

	@Column(name = "id_usuario", nullable = false)
	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SdmRolXUsuarioId))
			return false;
		SdmRolXUsuarioId castOther = (SdmRolXUsuarioId) other;

		return (this.getIdRol() == castOther.getIdRol())
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdRol();
		result = 37 * result + (int) this.getIdUsuario();
		return result;
	}

}
