package org.domain.sdm.entity;

// Generated Jul 16, 2014 12:05:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SdmTipoServicio generated by hbm2java
 */
@Entity
@Table(name = "SDM_tipo_servicio")
public class SdmTipoServicio implements java.io.Serializable {

	private long id;
	private String descripcion;
	private boolean activo;
	private Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles = new HashSet<SdmInformeViaticoDetalle>(
			0);

	public SdmTipoServicio() {
	}

	public SdmTipoServicio(long id, String descripcion, boolean activo) {
		this.id = id;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public SdmTipoServicio(long id, String descripcion, boolean activo,
			Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles) {
		this.id = id;
		this.descripcion = descripcion;
		this.activo = activo;
		this.sdmInformeViaticoDetalles = sdmInformeViaticoDetalles;
	}
	
	public SdmTipoServicio(SdmTipoServicio sdmTipoServicio) {
		this.id = sdmTipoServicio.id;
		this.descripcion = sdmTipoServicio.descripcion;
		this.activo = sdmTipoServicio.activo;
		this.sdmInformeViaticoDetalles = sdmTipoServicio.sdmInformeViaticoDetalles;
	}

	

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sdmTipoServicio")
	public Set<SdmInformeViaticoDetalle> getSdmInformeViaticoDetalles() {
		return this.sdmInformeViaticoDetalles;
	}

	public void setSdmInformeViaticoDetalles(
			Set<SdmInformeViaticoDetalle> sdmInformeViaticoDetalles) {
		this.sdmInformeViaticoDetalles = sdmInformeViaticoDetalles;
	}

}
